### ISSUE TITLE
Gesture back implementation

### ISSUE THREAD

**Issue by haileyleonard** [BrianJr03/apfp_app#40]
As a user, I should be able to navigate backwards through the app by using gestures. 

- Gesturing back should not exit the app at any point.
- Gesturing back from a page on the nav bar should send a user to the home screen.
- Gesturing back on a nested page should send them to the main page of that section (ex. gesturing back on a specific exercise video should send them back to all at-home exercise videos).

**Comment by cpvanlue** [comment]
Turning on back gestures may cause issues with orientation lock when gesturing back from individual exercise video page -- this is why I initially turned it off. When rotated sideways and gesturing back, the unlocked orientation remained for me on scenes where it should've been locked. Something to keep an eye out for.
